chore(configuradorfnmt): bump temurin-jre-bin
"Temurin 23 has been removed as it has reached its end of life"; # Added 2025-11-04

Trying to run `configuradorfnmt` against the officially recommended Java
17 (with Temurin 27) yields this error:

```
Error: LinkageError occurred while loading main class es.gob.fnmt.cert.certrequest.CertRequest
	java.lang.UnsupportedClassVersionError: es/gob/fnmt/cert/certrequest/CertRequest has been compiled by a more recent version of the Java Runtime (class file version 66.0), this version of the Java Runtime only recognizes class file versions up to 61.0
```

Temurin 25 is the only version that I’ve managed to get it working with
configuradorfnmt.  Any attempts with prior releases produces an error
similar to the one shown above.